### ISSUE TITLE
Is this wokring 

### ISSUE THREAD

**Issue by anethema** [Matroxt/one-pace-to-plex#14]
I just end up with the episodes spread over a bunch of normal "Seasons" and of course all the episode descriptions are wrong.

https://i.imgur.com/EQ73Lso.jpeg

Like in Season 2: https://i.imgur.com/fctTMbt.jpeg

Episode 2 shows shanks, but in season 2 for some reason, but it is actually the fight with buggy which of course is later.

Is this actually working for anyone?

**Comment by Matroxt** [comment]
Hey there

It worked as intended as far as I can see from your season 2 screenshot.

Let me explain;
The current release for the Orange Town arc (aka season 2 because it is the 2nd arc) of One Pace contains 3 episodes:
| One Pace Episode | One Pace title           | TVDB absolute episodes equivalent |
|------------------|--------------------------|-----------------------------------|
| 1                | Enter: Nami              | 4 to 5                            |
| 2                | Treasure                 | 6 & 7                             |
| 3                | Pirate Buggy "the Clown" | 8                                 |

As explained in the README, this script renames files to match those absolute orders from TVDB, where we can get metadata.
That's why your episodes have a correct title and description.

I can understand the annoyance of seeing Shanks in the thumbnail as part of the Orange Town arc since he should be in Romance Down, but that's due to how the official release of One Piece mixed Shanks and early Orange Town in the official episode 4.

The One Pace team obviously cut Shanks from that episode and put him in their episode 3. If you start the episode in Plex, you'll not see Shanks anywhere.

It is pretty much a tradeoff of this method, we take metadata form TVDB and sometimes it'll look a little weird.
However as a general rule, the episode should be fairly well split in arcs/seasons.

Let me know if that clears up the confusion.

**Comment by Matroxt** [comment]
Stale
