### ISSUE TITLE
Have you, or anyone, gotten this to work with Jellyfin? & how do you handle incomplete One Pace arcs?

### ISSUE THREAD

**Issue by Kylar514** [Matroxt/one-pace-to-plex#15]
Title basically.

How does this handle the incomplete arcs, like Arabasta, that seems to be incomplete on the one pace website..?

and

Anyone get this working with Jellyfin?  I'd imagine it should work, but not 100% sure.  Was looking to try, but dont want to try in vain.

**Comment by Matroxt** [comment]
Hey there

Incomplete arcs or not, it doesn't really matter.

Say you have episode 1 to 3 of the Arabasta arc, the script will rename the files to match the absolute order of the TVDB.

Plex will pickup whatever file there is and using Absolute Series Scanner and HAMA agent, it will fetch the metadata for the episodes.

Missing episodes will be just that, missing from Plex. As the One Pace team releases new episode, you can run the script against that new episode, it will get renamed with the right nomenclature, then you copy paste it in you arc directory and Plex will pick it up.


As for Jellyfin, I'm not sure it would work very well since ASS and HAMA are not compatible (AFAIK).
The renaming might be useful to get the right metadata on you episodes, but you won't be able to organize seasons as arcs.
