### ISSUE TITLE
Fishman Island

### ISSUE THREAD

**Issue by JefferyRose** [Matroxt/one-pace-to-plex#2]
It incorrectly gives the wrong episode number for the fishman island episodes

**Comment by JefferyRose** [comment]
"Fishman Island": {
    "01": "E523-E524",
    "02": "E524-E526",
    "03": "E526-E527",
    "04": "E528-E529",
    "05": "E530-E531",
    "06": "E532-E533",
    "07": "E533-E534",
    "08": "E535-E537",
    "09": "E538-E539",
    "10": "E540-E541",
    "11": "E543-E545",
    "12": "E545-E546",
    "13": "E547-E550",
    "14": "E550-E551",
    "15": "E552-E553",
    "16": "E554-E556",
    "17": "E556-E558",
    "18": "E559-E560",
    "19": "E561-E562",
    "20": "E563-E567",
    "21": "E562-E567",
    "22": "E567-E569",
    "23": "E570-E571",
    "24": "E572-E573"

**Comment by Matroxt** [comment]
Thanks for opening the issue!

I edited your suggested order because Plex doesn't like when different video files have episode overlaps.
Eg:
```
"06": "E532-E533",
"07": "E533-E534",
```
Here episode 533 could cause problems so I made a choice to isolate it to one One Pace episode even if it's not as accurate. The goal of the repo is to make it play nice with Plex to this takes priority.
