### ISSUE TITLE
Mostly everything is just one big mess

### ISSUE THREAD

**Issue by HeavenlyDemon100** [Matroxt/one-pace-to-plex#7]
Hey. As far as I can tell, I named everything correctly, arranged it as you said, used ASS as the scanner and Hama as the agent and everything is a big mess.
Some episodes have the right title but not in the right season, some seasons are completely wrong in their matching, and much much more... Is this a mistake on my side? Did anything change since you made this?

### Screenshots of my setup:

![image](https://github.com/Matroxt/one-pace-to-plex/assets/107574383/ed02c4e0-827b-4a60-85b3-c69349f2ef0b)

![image](https://github.com/Matroxt/one-pace-to-plex/assets/107574383/117ab0ea-16c2-435f-9d15-c17e85fc83b8)

![image](https://github.com/Matroxt/one-pace-to-plex/assets/107574383/3ee0788b-92eb-4b65-840d-b8f98a4606a7)

### Screenshots showing things not working as intended:

(Just an example of this problem, Little Garden arc getting detected as Long Ring and Water 7. Some episodes are named correctly, some are totally different)

![image](https://github.com/Matroxt/one-pace-to-plex/assets/107574383/bc7dfb2a-c89b-4d87-8bcc-8a2df1873246)

![image](https://github.com/Matroxt/one-pace-to-plex/assets/107574383/c6873ead-de12-4ff4-8aeb-a06fc17b634b)

![image](https://github.com/Matroxt/one-pace-to-plex/assets/107574383/2bfe9971-56c1-40a1-8640-6fa8067d7bf5)

And this is only one of many occasions where this issue happens, where a bunch of seasons and episodes are messed up like this. I tried messing with settings, Plex Dance'ed multiple times, but nothing works :(

I just hope that this method still works because it's goddamn annoying to have to categorize this as "Other Videos" library in Plex, having no metadata and everything else.

**Comment by Matroxt** [comment]
Hey!

Yeah this should still work no problem.

Here's a couple things to confirm:

- Outside Plex:
  - Do files looks to have the proper episode numbers? If you take say `One.Piece.E91-E92.480p.mkv`, is it the first episode or the Arabasta arc (like the actual video content)?
  - If the episode numbers are off, that's would be problem 1 for sure. Though the script should've done a somewhat good job if I didn't mess up.
  - `tvdb4.mapping` is in ever arc directory
  
- In Plex:
  - Did you load the `One Pace` directory or the `One Piece [tvdb4-81797]` in your anime library? Personally I just have an `anime` directory and put mine in there, not sure how the `One Pace` directory fits in this story for you.
  - Make sure that anime library has those HAMA and ASS scanner/agent setup.
  
I would also take a look at the troubleshooting section of [ASS documentation](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md#troubleshooting)

**Comment by HeavenlyDemon100** [comment]
Hey man thanks for the reply!

>Do files looks to have the proper episode numbers? If you take say One.Piece.E91-E92.480p.mkv, is it the first episode or the Arabasta arc (like the actual video content)?

Well if I understood you right, yeah the filename episode numbers match the actual video.
One thing is I didn't rename the episodes myself. I downloaded a batch someone uploaded to Nyaa, with all of One Pace with the proper renaming already done as your guide suggests with the script and all. I can link it here if it's allowed (piracy obvs), from what I've checked his renames were correct.

>If the episode numbers are off, that's would be problem 1 for sure. Though the script should've done a somewhat good job if I didn't mess up.

answered above

>tvdb4.mapping is in ever arc directory

Yeah, every arc has tvdb4.mapping

>Did you load the One Pace directory or the One Piece [tvdb4-81797] in your anime library? Personally I just have an anime directory and put mine in there, not sure how the One Pace directory fits in this story for you.

About this, I have an anime library with all of my anime, but I don't like how ASS and Hama are handleing it, I prefer the default plex matching.
So I made a library just for One Pace (Called One Pace), in Plex set the library for that folder, and put One Piece [tvdb4-81797] as the only show in that library.

So my folder structure looks like this:
```
Multimedia
        Ariel
           One Pace
              One Piece [tvdb4-81797]
                       Arc 10 - Little Garden
                       Arc XX
                       Arc 31 - Reverie 
```



>Make sure that anime library has those HAMA and ASS scanner/agent setup.

Yeah I checked, also you can see in the screenshot

**Comment by HeavenlyDemon100** [comment]
?

**Comment by Truth-** [comment]
This is due to a collision of episodes in episodes-reference.json compared to tvdb4.mapping.

tvdb4.mapping:
10|0070|0077|Little Garden Arc
11|0078|0090|Drum Island Arc

episodes-reference.json:
  "Little Garden": {
    "01": "E70-E71",
    "02": "E72",
    "03": "E73-E74",
    "04": "E75-E76",
    "05": "E77-E78"
  },
  "Drum Island": {
    "01": "E79",
    "02": "E80-E81",
    "03": "E82-E83",
    "04": "E84",
    "05": "E85",
    "06": "E86-E87",
    "07": "E88-E89",
    "08": "E90",
    "09": "E91"
  },


This means episode Little Garden 05 which is episodes 77-78 will be placed in Drum Island due to the tvdb4.mapping

**Comment by Matroxt** [comment]
Good catch @Truth-!

I fixed the reference files [in this commit](https://github.com/Matroxt/one-pace-to-plex/commit/19418d50ae30b145b22f17ea267e0e3f8cf8661b).

@HeavenlyDemon100 Try renaming those 2 files:
- `One.Piece.E77-E78.480p.mvk` -> `One.Piece.E77.480p.mvk`
- `One.Piece.E79.480p.mvk` -> `One.Piece.E78-E79.480p.mvk`

**Comment by HeavenlyDemon100** [comment]
Hey guys thanks for the fixes!
I tried it and it did seem to work for this specific instance, the thing is I think this needs to be fixed in multiple arcs. This problem also occurs in Drum Island & Alabasta.

(Currently In Plex): The first episode of Alabasta is named "Goodbye Drum Island! I'm Going Out to Sea!"
(The Actual episode name Plex should give it): "Alabasta's Hero and a Ballerina on the Ship!"

From what I can see the episode names given by Hama and ASS are (sometimes) wrong and their actual match is the episode before/after it.

**Comment by Matroxt** [comment]
Yep that indeed was wrong,[ just fixed it here](https://github.com/Matroxt/one-pace-to-plex/commit/483a038516c3ad6ea44fd7432ea82d1374345883)

You'll need to correct your `tvdb4.mapping` files with this:
```
11|0078|0091|Drum Island Arc
12|0092|0130|Arabasta Arc
```

**Comment by HeavenlyDemon100** [comment]
So basically we need to manually go through everything and see where this problem occurs? I've seen this happen in multiple places

**Comment by Matroxt** [comment]
Thanks for your patience, I reviewed everything and there was indeed more errors.

Probably should've done that on the first report 😶

I fixed it all in [my latest commit](https://github.com/Matroxt/one-pace-to-plex/commits/main), but unfortunately, you'll need to fix some of those manually.

The biggest error is that `Water Seven 20` had the episode 312, which is completely wrong, that's the last episode for `Enies Lobby 25`. Since they both shared the same number when you ran the script, one got overwritten for sure, you'll need to redownload one of them .

One other issue was at Fishman Island/Punk Hazard, but that's easy to fix:
| Arc            | Before                        | After                        |
|----------------|-------------------------------|------------------------------|
| Enies Lobby    | One.Piece.E263-E264.1080p.mvk | One.Piece.E264.1080p.mvk     |
| Fishman Island | One.Piece.E572-E574.720p.mvk  | One.Piece.E572-E573.720p.mvk |
| Punk Hazard    | One.Piece.E574-E579.720p.mvk  | One.Piece.E579.720p.mvk      |

You'll also want to replace the` tvdb4.mapping` file at least in your Punk Hazard and Dressrosa Arc directories with these changes:
```
27|0579|0627|Punk Hazard Arc
28|0628|0746|Dressrosa Arc
```
You can change it in other directories, but it shouldn't impact anything.

As far as I can tell, this will resolve all outstanding issues.

**Comment by Matroxt** [comment]
Seems like this issue is stale, so I'll close this.

Just FYI, there's some breaking changes coming to the repo, the One Pace team added 2 arcs:
- Buggy's Adventures
- Trials of Kobby-Meppo

Once I push those changes, you'll need to resync the `tvdb4.mapping` files and renumber the arcs directories accordingly.
